# K8s for calculator app / image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-deployment
spec:
  selector:
    matchLabels:
      app: calc
  replicas: 2 
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc
        image: srinivaskurecheti/devops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
